#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Add with the tags of most recent addition:"
  curcmd=`basename $0`
  echo "    $curcmd \"THING I NEED TO DO +project @context\""
  echo "      Append the tags of the most recently added item"
  echo "      to this item. If tags are different, resets."
  echo ""
  exit
}

# get the last line added and extract context
line=`sed -n '$ =' "$TODO_FILE"`
REGEX='[@|+][A-Za-z0-9]*'

echo "$line" | grep -o "$REGEX"